# Softmax Loss Calculation

In [9]:
import pandas as pd
import plotly
import plotly.plotly as py
import plotly.graph_objs as go
import numpy as np

## Helper Functions

In [15]:
def define_initial_data():

    return {'point_1': {'x1': -3, 'x2': 3, 'label': 0},
            'point_2': {'x1': 3, 'x2': 4, 'label': 0},
            'point_3': {'x1': 5, 'x2': 2, 'label': 0},
            'point_4': {'x1': -5, 'x2': -1, 'label': 1},
            'point_5': {'x1': -3, 'x2': -2, 'label': 1},
            'point_6': {'x1': -2, 'x2': -5, 'label': 1},
            'point_7': {'x1': 1, 'x2': -6, 'label': 2},
            'point_8': {'x1': 3, 'x2': -2, 'label': 2},
            'point_9': {'x1': 5, 'x2': -1, 'label': 2}}

In [49]:
def softmax(x):
    return np.exp(x) / np.sum(np.exp(x))

### Import data and define lambda for regularization

In [94]:
# data import
data = pd.DataFrame(define_initial_data()).T

# define the lambda
lmbda = 0.1

### Prepare the features and the targets

In [31]:
# one hot for the labels
y = np.zeros((9, 3))
y[np.arange(9), data['label']] = 1

In [32]:
# turn the inputs into matrix
X = np.array(data[['x1', 'x2']])

### Randonly select a set of weights

In [55]:
# define random weights
w = np.random.randn(2, 3) / 3

### Feedforward and calculate the error

In [56]:
# obtain the scores
z = X.dot(w)

In [57]:
# check the scores
z

array([[-0.16603629, -0.13952632, -0.49115925],
       [ 1.51991926, -0.75141003,  1.9814518 ],
       [ 1.63061012, -0.65839248,  2.3088913 ],
       [-1.43719827,  0.53111586, -2.09599237],
       [-1.13309556,  0.49685679, -1.55565393],
       [-1.46457383,  0.7979188 , -1.81773205],
       [-0.91171383,  0.68289188, -0.90077493],
       [ 0.35944815,  0.0122497 ,  0.70405819],
       [ 1.05037457, -0.27656262,  1.6701945 ]])

In [95]:
softmax_scores = np.zeros((9, 3))

# calculate the softmax scores for evrery training example
for i, score in enumerate(z):
    softmax_scores[i] = softmax(z[i])

# check the scores
softmax_scores

array([[ 0.36372855,  0.37349993,  0.26277152],
       [ 0.37179165,  0.03835958,  0.58984876],
       [ 0.32553615,  0.03299879,  0.64146505],
       [ 0.11525952,  0.82509656,  0.05964392],
       [ 0.14795089,  0.75508683,  0.09696228],
       [ 0.08842146,  0.84946547,  0.06211307],
       [ 0.14414653,  0.71012148,  0.14573199],
       [ 0.32070766,  0.22663291,  0.45265943],
       [ 0.32011454,  0.08492272,  0.59496274]])

In [97]:
# get the softmax score of the correct class
scores_yi = np.zeros((9, 3))
scores_yi[np.arange(9), data['label']] = softmax_scores[np.arange(9), data['label']]
s = scores_yi.flatten().reshape((-1, 1))
s = s[~np.all(s == 0, axis=1)]
s

array([[ 0.36372855],
       [ 0.37179165],
       [ 0.32553615],
       [ 0.82509656],
       [ 0.75508683],
       [ 0.84946547],
       [ 0.14573199],
       [ 0.45265943],
       [ 0.59496274]])

In [100]:
# get the cross entropy loss
loss = -np.log(s) + lmbda * np.sum(np.square(w))
loss